var accountInfo = {
    "customerName": "shirleyPatridge",
    "customerURL":"https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
    "currentBalanceTotal": "-1,692.00",
    "balanceTotal": "-162.00",
    "transactionList":[
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Registration Fee",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Payments Credit Card Master Card *5656",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Registration Fee",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Payments Credit Card Master Card *5656",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Registration Fee",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Payments Credit Card Master Card *5656",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  }, {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Registration Fee",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Payments Credit Card Master Card *5656",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Registration Fee",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Payments Credit Card Master Card *5656",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  },
  {
      "Amount": -1,
      "Amount@OData.Community.Display.V1.FormattedValue": "($1.00)",
      "Credit": "($1.00)",
      "Date": "2019-01-30",
      "Date@OData.Community.Display.V1.FormattedValue": "1/30/2019",
      "Debit": "",
      "ID": "e8eed800-e638-e811-810c-c4346bad526c",
      "ID@OData.Community.Display.V1.FormattedValue": "Greg Philip - Algebra Fundamentals",
      "ListLength": 271,
      "Name": "Cancelled Enrollment",
      "PaymentMethod": "Greg Philip - Algebra Fundamentals",
      "TransactionDate": "1/30/2019",
      "TransactionURL": "https://dev1sylvanhub.crm.dynamics.com/CRMReports/viewer/drillopen.aspx?ID={e8eed800-e638-e811-810c-c4346bad526c}&LogicalName=hub_fin_bill",
      "TrasactionType": 4,
      "TrasactionType@OData.Community.Display.V1.FormattedValue": "Discount",
      "Type": "Discount",
      "_transactioncurrencyid_value": "403afced-3006-e711-80e9-c4346bacfb24",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar"
  }
    ],
    "ListLength": 420,
    "paymentTotal":"$1162",
    "chargeTotal":"($16)",
    "creditTotal":"$600"
}

function Data() {
    this.getAccountLedger = function (startingIndex, pageSize) {
        return accountInfo;
    }

    this.exportTransaction = function () {
        return true;
    }
}